# Permalinks
permalink:        pretty

# Setup
title:            'Austin Transportation Open Data and Performance Hub'
tagline:          'Open Data Projects at the Austin Transportation Department'
description:      ''
url:            https://johnclary.github.io/transportation/

author:
  name:           ''
  url:            ''

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/cityofaustin/transportation
